name: Build and Test Student Grades App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install NPM Dependencies
      run: npm install
    - name: Run Unit Tests
      run: npm run test:unit
    - name: Display SoftUni Username
      run: echo "amended"

  run-ui-tests:
    needs: build-and-run-unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install NPM Dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Run Application
      run: npm run start &  # & is used to run app in the background
    - name: Run UI Tests
      run: npm run test:ui

  # deploy-to-render:
  #   runs-on: ubuntu-latest
  #   needs: run-ui-tests
  #   steps:
  #   - name: Deploy to production
  #     uses: johnbeynon/render-deploy-action@v0.0.8
  #     with:
  #       service-id: ${{ secrets.RENDER_SERVICE_ID }}
  #       api-key: ${{ secrets.RENDER_API_KEY }}
  #       # wait-for-success: true  # Seems to not be working
